name = "personal-site-astro"
pages_build_output_dir = "./dist"
compatibility_date = "2025-03-12"

# Node.js compatibility
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "STATIC_CONTENT"

[vars]
NODE_VERSION = "22"
